### ISSUE TITLE
remove-sting fails on CCL

### ISSUE THREAD

**Issue by Symbolics** [Islam0mar/cl-cxx#3]
The call to `search` in [remove-string](https://github.com/Islam0mar/cl-cxx/blob/990c2f0b010db7beb158e2aa7596c7be48a8f657/src/utilities.lisp#L37) fails because both `:test` and `:test-not` keyword parameters are passed in, which are flagged as incompatible with each other.

Looking at the intended function of `remove-string`, I cannot see where `:test-not` would ever be a relevant keyword, and I have removed this keyword locally without any noticeable effects.

In looking at `remove-string` generally, I do not understand how all of the existing keyword parameters would be useful in removing a sub-string from a string. Depending on how much string manipulation is required [ppcre](https://github.com/edicl/cl-ppcre) or [split-sequence](https://github.com/sharplispers/split-sequence) might be considered .

**Comment by Islam0mar** [comment]
I am using this for reference:
 [search](http://www.lispworks.com/documentation/HyperSpec/Body/f_search.htm#search)
