### ISSUE TITLE
C++ Lambda expressions in .defmethod leads to infinite recursion overflow upon cxx:add-package

### ISSUE THREAD

**Issue by ormf** [Islam0mar/cl-cxx#6]
C++ Lambda expressions in .defmethod lead to infinite recursion overflow upon cxx:add-package

This is the definition in the cpp file:

  pack.defclass<Link::SessionState, false>("SessionState")
    .defmethod("setTempo", [](SessionState &sessionState, const double tempo, const uint64_t time)
         { sessionState.setTempo(tempo, std::chrono::microseconds(time)); })

The code compiles fine. Is there a way around?

**Comment by Islam0mar** [comment]
Could you provide a working example to investigate ?

**Comment by ormf** [comment]
will do, but will take some time...

**Comment by ormf** [comment]
FYI: I'm offline for a couple of days.

**Comment by Islam0mar** [comment]
Hey wait.
I have changed `CLCXX` to accept a macro before functions. update yourself with the latest.
```c++
pack.defclass<Link::SessionState, false>("SessionState")
.defmethod("setTempo", F_PTR([](SessionState &sessionState, const double tempo, const uint64_t time)
{ sessionState.setTempo(tempo, std::chrono::microseconds(time)); }))
```
Old version has a bug in method with a lambda. @ https://github.com/Islam0mar/CLCXX/blob/dc72e408b9c9004c1f7fcc38ad73b50385a0af07/include/clcxx/package.hpp#L379.

**Comment by Islam0mar** [comment]
That should work well when using latest `cl-cxx` and `CLCXX`.

**Comment by ormf** [comment]
Doesn't seem to work here. I uploaded a minimal example [here](https://github.com/ormf/cl-link) (Instructions to reproduce in the README). The code causing the overflow is the lambda expression in lines 21-22 of the file `cl-link/link-clcxx/src/link-clcxx.cpp`. Commenting these lines out makes the overflow disappear here. Any suggestions?

**Comment by Islam0mar** [comment]
Kindly replace https://github.com/ormf/cl-link/tree/master/link-clcxx/include/clcxx with the lastest commit from [here](https://github.com/Islam0mar/CLCXX). Also change lib name to `libClCxx` and add `F_PTR(&...)` before every function/mem_function/lambda.

**Comment by Islam0mar** [comment]
Class lambda is working and tested [here](https://github.com/Islam0mar/CLCXX/blob/master/tests/test.cpp#L169).

reopen if this isn't the case.
